const gateLogic={AND:(a,b)=>a&&b,OR:(a,b)=>a||b,XOR:(a,b)=>!!a!==!!b,NAND:(a,b)=>!(a&&b),NOR:(a,b)=>!(a||b),NOT:a=>!a};
const ns='http://www.w3.org/2000/svg';
let levels=[],idx=Number(localStorage.pp_level||0),level=null,player={},started=Date.now(),timer=null,totalScore=Number(localStorage.pp_score||0),won=false,selectedPiece=null,dragGhost=null,dragData=null;
const $=id=>document.getElementById(id);
const svg=$('svg'),tray=$('tray'),starsEl=$('stars'),levelTitle=$('levelTitle'),scoreText=$('scoreText'),timeText=$('timeText'),instruction=$('instruction'),overlay=$('nextOverlay');
init();
async function init(){try{const r=await fetch('levels.json',{cache:'no-store'});const data=await r.json();levels=data.levels||[];if(!levels.length)throw new Error('No levels in levels.json');idx=Math.min(idx,levels.length-1);bind();loadLevel(idx);}catch(e){document.body.innerHTML='<div class="error">Could not load levels.json<br><br>'+e.message+'</div>';}}
function bind(){
  $('resetBtn').onclick=()=>loadLevel(idx);
  $('backBtn').onclick=()=>{idx=Math.max(0,idx-1);localStorage.pp_level=idx;loadLevel(idx)};
  $('nextBtn').onclick=()=>{idx=(idx+1)%levels.length;localStorage.pp_level=idx;loadLevel(idx)};
}
function loadLevel(i){level=JSON.parse(JSON.stringify(levels[i]));player={};won=false;started=Date.now();overlay.style.display='none';levelTitle.textContent=level.title||('LEVEL '+level.id);instruction.innerHTML=(level.instruction||'MAKE GOAL ON').replace('GOAL ON','GOAL <span class="go">ON</span>');if(timer)clearInterval(timer);timer=setInterval(tick,250);render();tick();}
function tick(){const s=Math.floor((Date.now()-started)/1000);timeText.textContent=fmt(s);renderStars(currentStars());if(!won)scoreText.textContent=totalScore+currentLevelScore();}
function fmt(s){return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')}
function currentStars(){const t=level.starTimeSeconds||45;const r=(Date.now()-started)/1000/t;if(r<=.18)return 5;if(r<=.32)return 4.5;if(r<=.46)return 4;if(r<=.60)return 3.5;if(r<=.75)return 3;if(r<=.92)return 2.5;if(r<=1.12)return 2;if(r<=1.35)return 1.5;return 1}
function currentLevelScore(){return Math.round((level.baseScore||100)*(currentStars()/5))}
function renderStars(v,target=starsEl){target.innerHTML='';for(let i=1;i<=5;i++){const s=document.createElement('span');s.className='star';let fill=Math.max(0,Math.min(1,v-(i-1)));s.style.setProperty('--fill',(fill*100)+'%');s.textContent='★';target.appendChild(s)}}
function resolve(){const vals={};for(const [k,v] of Object.entries(level.circuit.inputs||{})){vals[k]=(k in player)?!!Number(player[k]):(v===null?null:!!Number(v));}for(const n of level.circuit.nodes||[]){const type=(n.id in player)?player[n.id]:n.type;if(!type){vals[n.id]=null;continue}const inputVals=n.inputs.map(id=>vals[id]);if(inputVals.some(v=>v===null||v===undefined)){vals[n.id]=null;continue}vals[n.id]=gateLogic[type](...inputVals)}return {values:vals,output:vals[level.circuit.output]}}
function render(){svg.innerHTML='';const res=resolve();drawWires(res.values);drawInputs(res.values);drawNodes(res.values);drawGoal(res.output);renderTray();checkWin(res.output);}
function checkWin(output){if(won)return;if(output!==null&&Number(output)===Number(level.goal)){won=true;const add=currentLevelScore();totalScore+=add;localStorage.pp_score=totalScore;scoreText.textContent=totalScore;clearInterval(timer);renderStars(currentStars(),$('winStars'));setTimeout(()=>overlay.style.display='grid',450)}}
function getP(id){const l=level.circuit.layout||{};const p=(l.inputs&&l.inputs[id])||(l.nodes&&l.nodes[id])||(id==='GOAL'&&l.goal);return p||{x:50,y:50}}
function wirePath(a,b){const dx=Math.abs(b.x-a.x),mid=a.x+dx*.45;return `M ${a.x} ${a.y} C ${mid} ${a.y}, ${mid} ${b.y}, ${b.x} ${b.y}`}
function drawWires(vals){for(const n of level.circuit.nodes||[]){const np=getP(n.id);for(const src of n.inputs){const sp=getP(src);drawPath(wirePath({x:sp.x+5,y:sp.y},{x:np.x-9,y:np.y}),vals[src])}}const out=getP(level.circuit.output),g=level.circuit.layout.goal||{x:86,y:50};drawPath(wirePath({x:out.x+9,y:out.y},{x:g.x-8,y:g.y}),vals[level.circuit.output])}
function drawPath(d,on){svg.appendChild(el('path',{d,class:'wire '+(on?'on':'')}))}
function drawInputs(vals){for(const [id,v] of Object.entries(level.circuit.inputs||{})){const p=getP(id),actual=(id in player)?player[id]:v,missing=actual===null;const g=el('g',{class:'inputGroup',transform:`translate(${p.x} ${p.y})`,'data-slot':id});g.appendChild(el('text',{x:0,y:-9,class:'inputLabel'},id));g.appendChild(el('circle',{cx:0,cy:0,r:7.4,class:'orbBase '+(missing?'orbDash ':'')+(vals[id]?'orbOn':'')}));g.appendChild(el('text',{x:0,y:1.1,class:'orbText '+(vals[id]?'on':'')},missing?'?':String(Number(vals[id]))));g.onclick=()=>placeSelected(id,'input');svg.appendChild(g)}}
function drawNodes(vals){for(const n of level.circuit.nodes||[]){const p=getP(n.id),type=(n.id in player)?player[n.id]:n.type,missing=!type;const g=el('g',{class:'nodeGroup',transform:`translate(${p.x} ${p.y})`,'data-slot':n.id});if(missing){g.appendChild(el('rect',{x:-8,y:-10,width:16,height:20,rx:4,class:'slotFill'}));g.appendChild(el('text',{x:0,y:1,class:'slotText'},'?'));g.onclick=()=>placeSelected(n.id,'gate')}else drawGateShape(g,type,0,0,vals[n.id]);svg.appendChild(g)}}
function drawGateShape(g,type,x,y,on){if(type==='AND'||type==='NAND'){g.appendChild(el('path',{d:`M ${x-9} ${y-10} L ${x} ${y-10} C ${x+12} ${y-10}, ${x+12} ${y+10}, ${x} ${y+10} L ${x-9} ${y+10} Z`,class:'gateFill '+(on?'winPulse':'')}));if(type==='NAND')g.appendChild(el('circle',{cx:x+12,cy:y,r:2.5,class:'gateFill'}));}
else if(type==='OR'||type==='NOR'||type==='XOR'){g.appendChild(el('path',{d:`M ${x-10} ${y-10} C ${x-2} ${y-9}, ${x+8} ${y-5}, ${x+12} ${y} C ${x+8} ${y+5}, ${x-2} ${y+9}, ${x-10} ${y+10} C ${x-5} ${y+3}, ${x-5} ${y-3}, ${x-10} ${y-10} Z`,class:'gateFill '+(on?'winPulse':'')}));if(type==='XOR')g.appendChild(el('path',{d:`M ${x-13} ${y-10} C ${x-8} ${y-3}, ${x-8} ${y+3}, ${x-13} ${y+10}`,class:'wire'}));if(type==='NOR')g.appendChild(el('circle',{cx:x+14,cy:y,r:2.5,class:'gateFill'}));}
else if(type==='NOT'){g.appendChild(el('path',{d:`M ${x-10} ${y-10} L ${x+9} ${y} L ${x-10} ${y+10} Z`,class:'gateFill '+(on?'winPulse':'')}));g.appendChild(el('circle',{cx:x+11.5,cy:y,r:2.5,class:'gateFill'}));}g.appendChild(el('text',{x:x,y:y+1,class:'gateText'},type));}
function drawGoal(output){const p=level.circuit.layout.goal||{x:86,y:50};const g=el('g',{class:'goalGroup '+(output?'winPulse':''),transform:`translate(${p.x} ${p.y})`});g.appendChild(el('polygon',{points:'0,-10 7,-3 5,10 -5,10 -7,-3',fill:output?'#43ff59':'#12334c',stroke:'#91ff9e','stroke-width':1.8,class:'goalCrystal'}));g.appendChild(el('ellipse',{cx:0,cy:12,rx:10,ry:3.5,fill:'#061a20',stroke:'#43ff59','stroke-width':1.4}));g.appendChild(el('text',{x:0,y:24,class:'goalText'},'GOAL'));svg.appendChild(g)}
function renderTray(){tray.innerHTML='';(level.pieces||[]).forEach(p=>{const b=document.createElement('button');b.className='piece '+(p.kind==='input'?'inputPiece':'gatePiece');b.dataset.kind=p.kind;b.dataset.value=p.value;b.innerHTML=p.kind==='input'?`<span class="circle">${p.value}</span>`:miniGate(p.value);b.onclick=()=>selectPiece(b,p);b.onpointerdown=e=>startDrag(e,b,p);tray.appendChild(b)})}
function miniGate(type){if(type==='AND'||type==='NAND')return `<svg class="miniGate" viewBox="0 0 120 80"><path d="M25 16 L58 16 C102 16 102 64 58 64 L25 64 Z" fill="none" stroke="currentColor" stroke-width="5"/><text x="60" y="49" text-anchor="middle" font-size="24" font-weight="1000" fill="white">${type}</text></svg>`;if(type==='NOT')return `<svg class="miniGate" viewBox="0 0 120 80"><path d="M25 16 L92 40 L25 64 Z" fill="none" stroke="currentColor" stroke-width="5"/><circle cx="97" cy="40" r="5" fill="none" stroke="currentColor" stroke-width="5"/><text x="55" y="49" text-anchor="middle" font-size="22" font-weight="1000" fill="white">NOT</text></svg>`;return `<svg class="miniGate" viewBox="0 0 120 80"><path d="M24 16 C48 18 82 25 100 40 C82 55 48 62 24 64 C38 48 38 32 24 16 Z" fill="none" stroke="currentColor" stroke-width="5"/><text x="62" y="49" text-anchor="middle" font-size="24" font-weight="1000" fill="white">${type}</text></svg>`}
function selectPiece(btn,p){selectedPiece=p;document.querySelectorAll('.piece').forEach(x=>x.style.outline='');btn.style.outline='3px solid #ffd23f'}
function placeSelected(slot,kind){if(!selectedPiece||selectedPiece.kind!==kind)return;player[slot]=selectedPiece.value;selectedPiece=null;document.querySelectorAll('.piece').forEach(x=>x.style.outline='');render()}
function startDrag(e,btn,p){dragData=p;selectPiece(btn,p);dragGhost=btn.cloneNode(true);dragGhost.classList.add('ghost');document.body.appendChild(dragGhost);moveGhost(e);btn.setPointerCapture(e.pointerId);btn.onpointermove=moveGhost;btn.onpointerup=endDrag;}
function moveGhost(e){if(!dragGhost)return;dragGhost.style.left=e.clientX+'px';dragGhost.style.top=e.clientY+'px'}
function endDrag(e){if(dragGhost){dragGhost.remove();dragGhost=null}const target=document.elementFromPoint(e.clientX,e.clientY);let node=target&&target.closest('[data-slot]');if(node&&dragData){const slot=node.getAttribute('data-slot');const isInput=slot in (level.circuit.inputs||{});if((isInput&&dragData.kind==='input')||(!isInput&&dragData.kind==='gate')){player[slot]=dragData.value;dragData=null;render();return}}dragData=null;}
function el(tag,attrs={},text){const e=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')e.setAttribute('class',v);else e.setAttribute(k,v)}if(text!==undefined)e.textContent=text;return e}
